/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4KDYr6huqDN
 */
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { CardTitle, CardHeader, CardContent, Card } from '@/components/ui/card'
import { BookSVG, UsersSVG } from '@/components/svg/'

export function PageShell() {
  return (
    <div key='1' className='grid h-screen w-full grid-cols-[280px_1fr] overflow-hidden'>
      <div className='border-r bg-zinc-100/40 dark:bg-zinc-800/40'>
        <div className='px-4 py-6'>
          <h1 className='text-xl font-bold text-zinc-900 dark:text-zinc-50 mb-4 text-left'>Johnson Marine</h1>
          <nav className='flex flex-col items-start gap-4'>
            <Link
              className='flex items-center gap-3 rounded-lg px-3 py-2 text-zinc-500 transition-all hover:bg-zinc-200 dark:text-zinc-400 dark:hover:bg-zinc-700'
              href='#'
            >
              <BookSVG />
              Services
            </Link>
            <Link
              className='flex items-center gap-3 rounded-lg px-3 py-2 text-zinc-500 transition-all hover:bg-zinc-200 dark:text-zinc-400 dark:hover:bg-zinc-700'
              href='#'
            >
              <UsersSVG />
              Users
            </Link>
            <Link
              className='flex items-center gap-3 rounded-lg px-3 py-2 text-zinc-500 transition-all hover:bg-zinc-200 dark:text-zinc-400 dark:hover:bg-zinc-700'
              href='#'
            >
              <svg
                className=' h-4 w-4'
                fill='none'
                height='24'
                stroke='currentColor'
                strokeLinecap='round'
                strokeLinejoin='round'
                strokeWidth='2'
                viewBox='0 0 24 24'
                width='24'
                xmlns='http://www.w3.org/2000/svg'
              >
                <path d='m7.5 4.27 9 5.15' />
                <path d='M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z' />
                <path d='m3.3 7 8.7 5 8.7-5' />
                <path d='M12 22V12' />
              </svg>
              Parts
            </Link>
            <Link
              className='flex items-center gap-3 rounded-lg px-3 py-2 text-zinc-500 transition-all hover:bg-zinc-200 dark:text-zinc-400 dark:hover:bg-zinc-700'
              href='#'
            >
              <svg
                className=' h-4 w-4'
                fill='none'
                height='24'
                stroke='currentColor'
                strokeLinecap='round'
                strokeLinejoin='round'
                strokeWidth='2'
                viewBox='0 0 24 24'
                width='24'
                xmlns='http://www.w3.org/2000/svg'
              >
                <path d='M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z' />
                <circle cx='12' cy='12' r='3' />
              </svg>
              Settings
            </Link>
            <Link
              className='flex items-center gap-3 rounded-lg px-3 py-2 text-zinc-500 transition-all hover:bg-zinc-200 dark:text-zinc-400 dark:hover:bg-zinc-700'
              href='#'
            >
              <svg
                className=' h-4 w-4'
                fill='none'
                height='24'
                stroke='currentColor'
                strokeLinecap='round'
                strokeLinejoin='round'
                strokeWidth='2'
                viewBox='0 0 24 24'
                width='24'
                xmlns='http://www.w3.org/2000/svg'
              >
                <path d='M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20' />
              </svg>
              Guides
            </Link>
            <Link
              className='flex items-center gap-3 rounded-lg px-3 py-2 text-zinc-500 transition-all hover:bg-zinc-200 dark:text-zinc-400 dark:hover:bg-zinc-700'
              href='#'
            >
              <svg
                className=' h-4 w-4'
                fill='none'
                height='24'
                stroke='currentColor'
                strokeLinecap='round'
                strokeLinejoin='round'
                strokeWidth='2'
                viewBox='0 0 24 24'
                width='24'
                xmlns='http://www.w3.org/2000/svg'
              >
                <path d='M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2' />
                <circle cx='12' cy='7' r='4' />
              </svg>
              Profile
            </Link>
          </nav>
        </div>
      </div>
      <main className='flex flex-col overflow-auto p-6'>
        <div className='flex items-center justify-between py-2 px-4 mb-4 bg-white dark:bg-zinc-800 rounded-lg shadow-sm'>
          <div className='flex items-center gap-2'>
            <Link className='text-zinc-500 dark:text-zinc-400' href='#'>
              Dashboard
            </Link>
            <span className='text-zinc-500 dark:text-zinc-400'>{`>`}</span>
            <Link className='text-zinc-500 dark:text-zinc-400' href='#'>
              Profile
            </Link>
          </div>
          <div className='flex items-center justify-between w-1/3'>
            <input
              aria-label='Search'
              className='flex-grow bg-white dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-800 rounded-lg py-2 px-4 text-sm outline-none'
              placeholder='Search...'
              type='text'
            />
            <Button className='ml-2' variant='outline'>
              <svg
                className=' h-4 w-4'
                fill='none'
                height='24'
                stroke='currentColor'
                strokeLinecap='round'
                strokeLinejoin='round'
                strokeWidth='2'
                viewBox='0 0 24 24'
                width='24'
                xmlns='http://www.w3.org/2000/svg'
              >
                <circle cx='11' cy='11' r='8' />
                <path d='m21 21-4.3-4.3' />
              </svg>
            </Button>
          </div>
        </div>
        <div className='grid grid-cols-2 gap-4'>
          <Card className='flex relative'>
            <div className='absolute top-0 right-0 p-2'>
              <Button size='sm' variant='ghost'>
                <svg
                  className=' h-4 w-4'
                  fill='none'
                  height='24'
                  stroke='currentColor'
                  strokeLinecap='round'
                  strokeLinejoin='round'
                  strokeWidth='2'
                  viewBox='0 0 24 24'
                  width='24'
                  xmlns='http://www.w3.org/2000/svg'
                >
                  <circle cx='12' cy='12' r='10' />
                  <path d='M12 16v-4' />
                  <path d='M12 8h.01' />
                </svg>
                <span className='sr-only'>More information</span>
              </Button>
            </div>
            <CardHeader>
              <CardTitle className='text-sm'>Open Services</CardTitle>
            </CardHeader>
            <CardContent className='text-xs'>
              <p>Tracking data...</p>
            </CardContent>
          </Card>
          <Card className='flex relative'>
            <div className='absolute top-0 right-0 p-2'>
              <Button size='sm' variant='ghost'>
                <svg
                  className=' h-4 w-4'
                  fill='none'
                  height='24'
                  stroke='currentColor'
                  strokeLinecap='round'
                  strokeLinejoin='round'
                  strokeWidth='2'
                  viewBox='0 0 24 24'
                  width='24'
                  xmlns='http://www.w3.org/2000/svg'
                >
                  <circle cx='12' cy='12' r='10' />
                  <path d='M12 16v-4' />
                  <path d='M12 8h.01' />
                </svg>
                <span className='sr-only'>More information</span>
              </Button>
            </div>
            <CardHeader>
              <CardTitle className='text-sm'>Awaiting Customer</CardTitle>
            </CardHeader>
            <CardContent className='text-xs'>
              <p>Tracking data...</p>
            </CardContent>
          </Card>
        </div>
        <div className='flex-1 rounded-lg border border-zinc-200 border-dashed dark:border-zinc-800 pt-4'>
          <table className='w-full text-left'>
            <thead>
              <tr>
                <th className='p-2'>Service ID</th>
                <th className='p-2'>Customer Name</th>
                <th className='p-2'>Status</th>
                <th className='p-2'>Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr className='hover:bg-zinc-200 dark:hover:bg-zinc-700'>
                <td className='p-2'>12345</td>
                <td className='p-2'>John Doe</td>
                <td className='p-2'>Active</td>
                <td className='p-2'>
                  <Button className='bg-yellow-500 text-white' variant='outline'>
                    <svg
                      className=' h-4 w-4'
                      fill='none'
                      height='24'
                      stroke='currentColor'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                      strokeWidth='2'
                      viewBox='0 0 24 24'
                      width='24'
                      xmlns='http://www.w3.org/2000/svg'
                    >
                      <path d='M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z' />
                      <path d='m15 5 4 4' />
                    </svg>
                  </Button>
                  <Button className='bg-blue-500 text-white ml-2' variant='outline'>
                    <svg
                      className=' h-4 w-4'
                      fill='none'
                      height='24'
                      stroke='currentColor'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                      strokeWidth='2'
                      viewBox='0 0 24 24'
                      width='24'
                      xmlns='http://www.w3.org/2000/svg'
                    >
                      <path d='M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20' />
                    </svg>
                  </Button>
                </td>
              </tr>
              <tr className='hover:bg-zinc-200 dark:hover:bg-zinc-700'>
                <td className='p-2'>67890</td>
                <td className='p-2'>Jane Smith</td>
                <td className='p-2'>Inactive</td>
                <td className='p-2'>
                  <Button className='bg-yellow-500 text-white' variant='outline'>
                    <svg
                      className=' h-4 w-4'
                      fill='none'
                      height='24'
                      stroke='currentColor'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                      strokeWidth='2'
                      viewBox='0 0 24 24'
                      width='24'
                      xmlns='http://www.w3.org/2000/svg'
                    >
                      <path d='M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z' />
                      <path d='m15 5 4 4' />
                    </svg>
                  </Button>
                  <Button className='bg-blue-500 text-white ml-2' variant='outline'>
                    <svg
                      className=' h-4 w-4'
                      fill='none'
                      height='24'
                      stroke='currentColor'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                      strokeWidth='2'
                      viewBox='0 0 24 24'
                      width='24'
                      xmlns='http://www.w3.org/2000/svg'
                    >
                      <path d='M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20' />
                    </svg>
                  </Button>
                </td>
              </tr>
              <tr className='hover:bg-zinc-200 dark:hover:bg-zinc-700'>
                <td className='p-2'>11223</td>
                <td className='p-2'>Alice Johnson</td>
                <td className='p-2'>Active</td>
                <td className='p-2'>
                  <Button className='bg-yellow-500 text-white' variant='outline'>
                    <svg
                      className=' h-4 w-4'
                      fill='none'
                      height='24'
                      stroke='currentColor'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                      strokeWidth='2'
                      viewBox='0 0 24 24'
                      width='24'
                      xmlns='http://www.w3.org/2000/svg'
                    >
                      <path d='M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z' />
                      <path d='m15 5 4 4' />
                    </svg>
                  </Button>
                  <Button className='bg-blue-500 text-white ml-2' variant='outline'>
                    <svg
                      className=' h-4 w-4'
                      fill='none'
                      height='24'
                      stroke='currentColor'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                      strokeWidth='2'
                      viewBox='0 0 24 24'
                      width='24'
                      xmlns='http://www.w3.org/2000/svg'
                    >
                      <path d='M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20' />
                    </svg>
                  </Button>
                </td>
              </tr>
              <tr className='hover:bg-zinc-200 dark:hover:bg-zinc-700'>
                <td className='p-2'>44556</td>
                <td className='p-2'>Bob Williams</td>
                <td className='p-2'>Inactive</td>
                <td className='p-2'>
                  <Button className='bg-yellow-500 text-white' variant='outline'>
                    <svg
                      className=' h-4 w-4'
                      fill='none'
                      height='24'
                      stroke='currentColor'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                      strokeWidth='2'
                      viewBox='0 0 24 24'
                      width='24'
                      xmlns='http://www.w3.org/2000/svg'
                    >
                      <path d='M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z' />
                      <path d='m15 5 4 4' />
                    </svg>
                  </Button>
                  <Button className='bg-blue-500 text-white ml-2' variant='outline'>
                    <svg
                      className=' h-4 w-4'
                      fill='none'
                      height='24'
                      stroke='currentColor'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                      strokeWidth='2'
                      viewBox='0 0 24 24'
                      width='24'
                      xmlns='http://www.w3.org/2000/svg'
                    >
                      <path d='M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20' />
                    </svg>
                  </Button>
                </td>
              </tr>
              <tr className='hover:bg-zinc-200 dark:hover:bg-zinc-700'>
                <td className='p-2'>78901</td>
                <td className='p-2'>Charlie Brown</td>
                <td className='p-2'>Active</td>
                <td className='p-2'>
                  <Button className='bg-yellow-500 text-white' variant='outline'>
                    <svg
                      className=' h-4 w-4'
                      fill='none'
                      height='24'
                      stroke='currentColor'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                      strokeWidth='2'
                      viewBox='0 0 24 24'
                      width='24'
                      xmlns='http://www.w3.org/2000/svg'
                    >
                      <path d='M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z' />
                      <path d='m15 5 4 4' />
                    </svg>
                  </Button>
                  <Button className='bg-blue-500 text-white ml-2' variant='outline'>
                    <svg
                      className=' h-4 w-4'
                      fill='none'
                      height='24'
                      stroke='currentColor'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                      strokeWidth='2'
                      viewBox='0 0 24 24'
                      width='24'
                      xmlns='http://www.w3.org/2000/svg'
                    >
                      <path d='M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20' />
                    </svg>
                  </Button>
                </td>
              </tr>
              <tr className='hover:bg-zinc-200 dark:hover:bg-zinc-700'>
                <td className='p-2'>23456</td>
                <td className='p-2'>Diana Prince</td>
                <td className='p-2'>Inactive</td>
                <td className='p-2'>
                  <Button className='bg-yellow-500 text-white' variant='outline'>
                    <svg
                      className=' h-4 w-4'
                      fill='none'
                      height='24'
                      stroke='currentColor'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                      strokeWidth='2'
                      viewBox='0 0 24 24'
                      width='24'
                      xmlns='http://www.w3.org/2000/svg'
                    >
                      <path d='M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z' />
                      <path d='m15 5 4 4' />
                    </svg>
                  </Button>
                  <Button className='bg-blue-500 text-white ml-2' variant='outline'>
                    <svg
                      className=' h-4 w-4'
                      fill='none'
                      height='24'
                      stroke='currentColor'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                      strokeWidth='2'
                      viewBox='0 0 24 24'
                      width='24'
                      xmlns='http://www.w3.org/2000/svg'
                    >
                      <path d='M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20' />
                    </svg>
                  </Button>
                </td>
              </tr>
              <tr className='hover:bg-zinc-200 dark:hover:bg-zinc-700'>
                <td className='p-2'>34567</td>
                <td className='p-2'>Edward Cullen</td>
                <td className='p-2'>Active</td>
                <td className='p-2'>
                  <Button className='bg-yellow-500 text-white' variant='outline'>
                    <svg
                      className=' h-4 w-4'
                      fill='none'
                      height='24'
                      stroke='currentColor'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                      strokeWidth='2'
                      viewBox='0 0 24 24'
                      width='24'
                      xmlns='http://www.w3.org/2000/svg'
                    >
                      <path d='M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z' />
                      <path d='m15 5 4 4' />
                    </svg>
                  </Button>
                  <Button className='bg-blue-500 text-white ml-2' variant='outline'>
                    <svg
                      className=' h-4 w-4'
                      fill='none'
                      height='24'
                      stroke='currentColor'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                      strokeWidth='2'
                      viewBox='0 0 24 24'
                      width='24'
                      xmlns='http://www.w3.org/2000/svg'
                    >
                      <path d='M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20' />
                    </svg>
                  </Button>
                </td>
              </tr>
              <tr className='hover:bg-zinc-200 dark:hover:bg-zinc-700'>
                <td className='p-2'>45678</td>
                <td className='p-2' />
              </tr>
            </tbody>
          </table>
        </div>
      </main>
    </div>
  )
}
