import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { GlobalSearchProvider } from '@/context/global-search'
import { ModalProvider } from '@/context/modal'
import { TooltipProvider } from '@/components/ui/tooltip'
import { ModalContainer } from '@/components/ui/modal/modal-container'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <ModalProvider>
        <GlobalSearchProvider>
          <TooltipProvider>
            <body className={inter.className}>{children}</body>
          </TooltipProvider>
        </GlobalSearchProvider>
      </ModalProvider>
    </html>
  )
}
