/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OR8DHOvMW1w
 */
import {
  SelectValue,
  SelectTrigger,
  SelectLabel,
  SelectItem,
  SelectGroup,
  SelectContent,
  Select,
} from "@/components/ui/select";

export function TableRowsPerPage({
  setValue,
}: {
  setValue: (newValue: number) => void;
}) {
  return (
    <Select onValueChange={(value) => setValue(Number(value))}>
      <SelectTrigger className="w-[180px]">
        <SelectValue placeholder="Rows Per Page" />
      </SelectTrigger>
      <SelectContent>
        <SelectGroup>
          <SelectLabel>Rows Per Page</SelectLabel>
          <SelectItem value="5">5</SelectItem>
          <SelectItem value="10">10</SelectItem>
          <SelectItem value="15">15</SelectItem>
          <SelectItem value="20">20</SelectItem>
          <SelectItem value="-1">All</SelectItem>
        </SelectGroup>
      </SelectContent>
    </Select>
  );
}
